os:
  - linux

addons:
  apt:
    packages:
      - binutils-dev
      - libcurl4-openssl-dev
      - libdw-dev
      - libiberty-dev
      
language: bash

env:
  - PATH=${PATH}:${HOME}/kcov/bin

before_install:
  - wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz

install:
  - tar xzf master.tar.gz
  - cd kcov-master
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=${HOME}/kcov ..
  - make
  - make install
  - cd ../..
  - rm -rf kcov-master
  - mkdir -p coverage

before_script:
  - chmod u+rwx ./sind.sh
  - chmod u+rwx ./install.sh
  - chmod u+rwx ./test.sh

script:
  - shellcheck sind.sh
  - shellcheck test.sh
  - shellcheck install.sh
  - kcov coverage test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)